#ifndef TEMPLATEPLUGIN_GLOBAL_H
#define TEMPLATEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef TEMPLATEPLUGIN_LIB
# define TEMPLATEPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define TEMPLATEPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // TEMPLATEPLUGIN_GLOBAL_H
