#ifndef BLOBCOUNTERPLUGIN_GLOBAL_H
#define BLOBCOUNTERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef BLOBCOUNTERPLUGIN_LIB
# define BLOBCOUNTERPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define BLOBCOUNTERPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // BLOBCOUNTERPLUGIN_GLOBAL_H
